spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: file:./app/
cds:
  datasource.auto-config.enabled: false
  sql.supportedLocales: "*"
